export type AppCategory = "shindan" | "game";

export interface DiagnosisInfo {
  slug: string;
  title: string;
  shortTitle: string;
  emoji: string;
  description: string;
  image: string;
  gradient: string;
  bgGradient: string;
  border: string;
  hoverBorder: string;
  category?: AppCategory;
  createdAt?: string; // YYYY-MM-DD
}

// 人気診断（手動設定、週一でアナリティクス見て更新）
export const popularDiagnosisSlugs = [
  "menhera",
  "hsp",
  "adhd",
  "inkya-youkya",
  "neko-inu",
  "renai-brain",
];

// 人気ゲーム（手動設定、週一で更新）
export const popularGameSlugs = [
  "theomachia",
  "reaction-test",
  "memory-test",
  "flash-memory",
  "stroop-test",
  "tap-speed",
];

export const diagnoses: DiagnosisInfo[] = [
  {
    slug: "menhera",
    title: "メンヘラ度診断",
    shortTitle: "メンヘラ度診断",
    emoji: "🖤",
    description: "10個の質問であなたの恋愛依存度をチェック！",
    image: "/images/menhera/menhera-01-sad.png",
    gradient: "from-pink-400 to-purple-500",
    bgGradient: "from-pink-50 to-purple-50",
    border: "border-pink-200",
    hoverBorder: "hover:border-pink-400",
  },
  {
    slug: "oshi",
    title: "推し活スタイル診断",
    shortTitle: "推し活診断",
    emoji: "💖",
    description: "8個の質問であなたの推し活タイプを診断！",
    image: "/images/oshi/main-visual.png",
    gradient: "from-pink-500 to-purple-500",
    bgGradient: "from-pink-50 to-purple-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
  },
  {
    slug: "tanto-fan-oshi",
    title: "担当/ファン/推し診断",
    shortTitle: "担当/ファン/推し",
    emoji: "💜",
    description: "7つの質問であなたの応援スタイルを診断！",
    image: "/images/tanto-fan-oshi/logo.png",
    gradient: "from-pink-500 to-indigo-500",
    bgGradient: "from-purple-50 to-indigo-50",
    border: "border-indigo-200",
    hoverBorder: "hover:border-indigo-400",
  },
  {
    slug: "vtuber",
    title: "Vtuberオタクタイプ診断",
    shortTitle: "Vtuberオタク",
    emoji: "📺",
    description: "10個の質問であなたのリスナータイプを診断！",
    image: "/images/vtuber/main-visual.png",
    gradient: "from-purple-500 to-indigo-500",
    bgGradient: "from-purple-50 to-indigo-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
  },
  {
    slug: "gacha",
    title: "ソシャゲ課金スタイル診断",
    shortTitle: "課金スタイル",
    emoji: "💰",
    description: "10個の質問であなたの課金タイプを診断！",
    image: "/images/gacha/main-visual.png",
    gradient: "from-amber-500 to-orange-500",
    bgGradient: "from-amber-50 to-orange-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
  },
  {
    slug: "sns-fatigue",
    title: "SNS疲れタイプ診断",
    shortTitle: "SNS疲れ",
    emoji: "😵",
    description: "10個の質問であなたのSNS疲れタイプが判明！",
    image: "/images/sns-fatigue/main.png",
    gradient: "from-cyan-400 to-indigo-500",
    bgGradient: "from-cyan-50 to-indigo-50",
    border: "border-cyan-200",
    hoverBorder: "hover:border-cyan-400",
  },
  {
    slug: "otaku-kakuredo",
    title: "オタクの隠れ度診断",
    shortTitle: "隠れ度診断",
    emoji: "🥷",
    description: "10個の質問であなたのオタク隠蔽力を測定！",
    image: "/images/otaku-kakuredo/main.png",
    gradient: "from-orange-400 to-amber-600",
    bgGradient: "from-orange-50 to-amber-50",
    border: "border-orange-200",
    hoverBorder: "hover:border-orange-400",
  },
  {
    slug: "commu-ryoku",
    title: "オタクコミュ力診断",
    shortTitle: "コミュ力診断",
    emoji: "🗣️",
    description: "10個の質問であなたのオタクコミュ力を判定！",
    image: "/images/commu-ryoku/main.png",
    gradient: "from-teal-400 to-emerald-500",
    bgGradient: "from-teal-50 to-emerald-50",
    border: "border-teal-200",
    hoverBorder: "hover:border-teal-400",
  },
  {
    slug: "gamer-type",
    title: "ゲーマータイプ診断",
    shortTitle: "ゲーマータイプ",
    emoji: "🎮",
    description: "10個の質問であなたのゲーマースタイルを分析！",
    image: "/images/gamer-type/main.png",
    gradient: "from-red-500 to-orange-500",
    bgGradient: "from-red-50 to-orange-50",
    border: "border-red-200",
    hoverBorder: "hover:border-red-400",
  },
  {
    slug: "sanzai-type",
    title: "オタク散財タイプ診断",
    shortTitle: "散財タイプ",
    emoji: "💸",
    description: "10個の質問であなたのお金の消え方を診断！",
    image: "/images/sanzai-type/main.png",
    gradient: "from-yellow-500 to-purple-500",
    bgGradient: "from-yellow-50 to-purple-50",
    border: "border-yellow-200",
    hoverBorder: "hover:border-yellow-400",
  },
  {
    slug: "yoru-gata",
    title: "夜型オタク診断",
    shortTitle: "夜型オタク",
    emoji: "🌙",
    description: "10個の質問であなたの夜更かしタイプが判明！",
    image: "/images/yoru-gata/main.png",
    gradient: "from-indigo-600 to-purple-700",
    bgGradient: "from-indigo-50 to-purple-50",
    border: "border-indigo-200",
    hoverBorder: "hover:border-indigo-400",
  },
  {
    slug: "yami-zokusei",
    title: "闇属性診断",
    shortTitle: "闇属性",
    emoji: "⚔️",
    description: "10個の質問であなたの魂に宿る属性を覚醒！",
    image: "/images/yami-zokusei/main.png",
    gradient: "from-red-800 to-gray-900",
    bgGradient: "from-red-50 to-gray-50",
    border: "border-red-300",
    hoverBorder: "hover:border-red-500",
  },
  {
    slug: "neko-inu",
    title: "猫派犬派深層診断",
    shortTitle: "猫派犬派",
    emoji: "🐱",
    description: "10個の質問で本当の性格は猫か犬か判定！",
    image: "/images/neko-inu/main.png",
    gradient: "from-pink-400 to-blue-400",
    bgGradient: "from-pink-50 to-blue-50",
    border: "border-pink-200",
    hoverBorder: "hover:border-pink-400",
  },
  {
    slug: "inkya-youkya",
    title: "陰キャ陽キャスペクトラム診断",
    shortTitle: "陰キャ陽キャ",
    emoji: "🌓",
    description: "10個の質問であなたの陰陽スペクトラムを診断！",
    image: "/images/inkya-youkya/main.png",
    gradient: "from-purple-500 to-amber-500",
    bgGradient: "from-purple-50 to-amber-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
  },
  {
    slug: "shikou-type",
    title: "思考タイプ診断",
    shortTitle: "思考タイプ",
    emoji: "🧠",
    description: "10個の質問であなたの思考のクセを丸わかり診断！",
    image: "/images/shikou-type/main.png",
    gradient: "from-blue-500 to-amber-500",
    bgGradient: "from-blue-50 to-amber-50",
    border: "border-blue-200",
    hoverBorder: "hover:border-blue-400",
  },
  {
    slug: "sumaho-izon",
    title: "スマホ依存タイプ診断",
    shortTitle: "スマホ依存",
    emoji: "📱",
    description: "10個の質問であなたのスマホ依存スタイルを暴く！",
    image: "/images/sumaho-izon/main.png",
    gradient: "from-cyan-500 to-blue-600",
    bgGradient: "from-cyan-50 to-blue-50",
    border: "border-cyan-200",
    hoverBorder: "hover:border-cyan-400",
  },
  {
    slug: "motivation",
    title: "モチベーション源泉診断",
    shortTitle: "モチベーション",
    emoji: "⚡",
    description: "10個の質問であなたのやる気の源泉を特定！",
    image: "/images/motivation/main.png",
    gradient: "from-purple-500 to-amber-500",
    bgGradient: "from-purple-50 to-amber-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
  },
  {
    slug: "stress-taisho",
    title: "ストレス対処法タイプ診断",
    shortTitle: "ストレス対処法",
    emoji: "🌿",
    description: "10個の質問であなたのストレス対処タイプを診断！",
    image: "/images/stress-taisho/main.png",
    gradient: "from-green-500 to-purple-500",
    bgGradient: "from-green-50 to-purple-50",
    border: "border-green-200",
    hoverBorder: "hover:border-green-400",
  },
  {
    slug: "renai-brain",
    title: "恋愛脳レベル診断",
    shortTitle: "恋愛脳レベル",
    emoji: "💘",
    description: "10個の質問であなたの恋愛脳レベルを診断！",
    image: "/images/renai-brain/main.png",
    gradient: "from-pink-500 to-purple-500",
    bgGradient: "from-pink-50 to-purple-50",
    border: "border-pink-200",
    hoverBorder: "hover:border-pink-400",
  },
  {
    slug: "reaction-test",
    title: "反射神経テスト",
    shortTitle: "反射神経",
    emoji: "⚡",
    description: "5回の計測であなたの反射神経を測定！",
    image: "/images/reaction-test/main-visual.svg",
    gradient: "from-green-400 to-emerald-600",
    bgGradient: "from-green-50 to-emerald-50",
    border: "border-green-200",
    hoverBorder: "hover:border-green-400",
    category: "game",
  },
  {
    slug: "ten-seconds",
    title: "10秒チャレンジ",
    shortTitle: "10秒チャレンジ",
    emoji: "⏱️",
    description: "体内時計でぴったり10秒を目指せ！",
    image: "/images/ten-seconds/main-visual.svg",
    gradient: "from-purple-400 to-indigo-600",
    bgGradient: "from-purple-50 to-indigo-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
    category: "game",
  },
  {
    slug: "color-test",
    title: "色覚テスト",
    shortTitle: "色覚テスト",
    emoji: "🎨",
    description: "微妙に異なる色のパネルを見つけよう！",
    image: "/api/og/color-test",
    gradient: "from-pink-500 to-purple-600",
    bgGradient: "from-pink-50 to-purple-50",
    border: "border-pink-200",
    hoverBorder: "hover:border-pink-400",
    category: "game",
  },
  {
    slug: "tap-speed",
    title: "タップ速度テスト",
    shortTitle: "タップ速度",
    emoji: "👆",
    description: "10秒間で何回タップできる？連打速度を計測！",
    image: "/api/og/tap-speed",
    gradient: "from-purple-500 to-violet-600",
    bgGradient: "from-purple-50 to-violet-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
    category: "game",
  },
  {
    slug: "memory-test",
    title: "記憶力テスト",
    shortTitle: "記憶力テスト",
    emoji: "🧠",
    description: "パネルが光る順番を覚えてタップ！到達レベルで記憶力判定",
    image: "/api/og/memory-test",
    gradient: "from-amber-500 to-yellow-600",
    bgGradient: "from-amber-50 to-yellow-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
    category: "game",
  },
  {
    slug: "swipe-test",
    title: "スワイプ方向テスト",
    shortTitle: "スワイプテスト",
    emoji: "👆",
    description: "矢印の方向に素早くスワイプ！反射と判断力を測定",
    image: "/api/og/swipe-test",
    gradient: "from-cyan-400 to-blue-600",
    bgGradient: "from-cyan-50 to-blue-50",
    border: "border-cyan-200",
    hoverBorder: "hover:border-cyan-400",
    category: "game",
  },
  {
    slug: "dynamic-vision",
    title: "動体視力テスト",
    shortTitle: "動体視力",
    emoji: "👁️",
    description: "高速で動くターゲットを見極めろ！",
    image: "/api/og/dynamic-vision",
    gradient: "from-rose-400 to-red-600",
    bgGradient: "from-rose-50 to-red-50",
    border: "border-rose-200",
    hoverBorder: "hover:border-rose-400",
    category: "game",
  },
  {
    slug: "rhythm-test",
    title: "リズム感テスト",
    shortTitle: "リズム感",
    emoji: "🥁",
    description: "テンポに合わせてタップ！光が消えても維持できる？",
    image: "/api/og/rhythm-test",
    gradient: "from-violet-400 to-purple-600",
    bgGradient: "from-violet-50 to-purple-50",
    border: "border-violet-200",
    hoverBorder: "hover:border-violet-400",
    category: "game",
  },
  {
    slug: "stroop-test",
    title: "ストループテスト",
    shortTitle: "ストループ",
    emoji: "🧠",
    description: "文字の色と意味がバラバラ！脳がバグる体験",
    image: "/api/og/stroop-test",
    gradient: "from-red-400 to-orange-600",
    bgGradient: "from-red-50 to-orange-50",
    border: "border-red-200",
    hoverBorder: "hover:border-red-400",
    category: "game",
  },
  {
    slug: "flash-memory",
    title: "瞬間記憶テスト",
    shortTitle: "瞬間記憶",
    emoji: "📸",
    description: "一瞬表示される数字を記憶して順番に！",
    image: "/api/og/flash-memory",
    gradient: "from-sky-400 to-blue-600",
    bgGradient: "from-sky-50 to-blue-50",
    border: "border-sky-200",
    hoverBorder: "hover:border-sky-400",
    category: "game",
  },
  {
    slug: "kanji-yomi",
    title: "漢字読みテスト",
    shortTitle: "漢字読み",
    emoji: "📖",
    description: "この漢字、読める？難読漢字に挑戦！",
    image: "/api/og/kanji-yomi",
    gradient: "from-emerald-400 to-teal-600",
    bgGradient: "from-emerald-50 to-teal-50",
    border: "border-emerald-200",
    hoverBorder: "hover:border-emerald-400",
    category: "game",
  },
  {
    slug: "kanji-order",
    title: "書き順テスト",
    shortTitle: "書き順",
    emoji: "✒️",
    description: "正しい書き順、覚えてる？意外と間違えがち！",
    image: "/api/og/kanji-order",
    gradient: "from-stone-400 to-zinc-600",
    bgGradient: "from-stone-50 to-zinc-50",
    border: "border-stone-200",
    hoverBorder: "hover:border-stone-400",
    category: "game",
  },
  {
    slug: "math-speed",
    title: "計算スピードテスト",
    shortTitle: "計算スピード",
    emoji: "🧮",
    description: "30秒で何問解ける？暗算力を測定！",
    image: "/api/og/math-speed",
    gradient: "from-amber-400 to-orange-600",
    bgGradient: "from-amber-50 to-orange-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
    category: "game",
  },
  {
    slug: "accuracy-tap",
    title: "正確タップテスト",
    shortTitle: "正確タップ",
    emoji: "🎯",
    description: "小さくなるターゲットを正確にタップ！",
    image: "/api/og/accuracy-tap",
    gradient: "from-pink-400 to-rose-600",
    bgGradient: "from-pink-50 to-rose-50",
    border: "border-pink-200",
    hoverBorder: "hover:border-pink-400",
    category: "game",
  },
  {
    slug: "yojijukugo",
    title: "四字熟語テスト",
    shortTitle: "四字熟語",
    emoji: "📚",
    description: "空欄を埋めて四字熟語を完成させよう！",
    image: "/api/og/yojijukugo",
    gradient: "from-indigo-400 to-purple-600",
    bgGradient: "from-indigo-50 to-purple-50",
    border: "border-indigo-200",
    hoverBorder: "hover:border-indigo-400",
    category: "game",
  },
  {
    slug: "kotowaza",
    title: "ことわざテスト",
    shortTitle: "ことわざ",
    emoji: "📜",
    description: "ことわざの穴埋めに挑戦！",
    image: "/api/og/kotowaza",
    gradient: "from-amber-500 to-yellow-600",
    bgGradient: "from-amber-50 to-yellow-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
    category: "game",
  },
  {
    slug: "prefecture",
    title: "都道府県クイズ",
    shortTitle: "都道府県",
    emoji: "🗾",
    description: "県庁所在地・名物・地理をテスト！",
    image: "/api/og/prefecture",
    gradient: "from-green-400 to-emerald-600",
    bgGradient: "from-green-50 to-emerald-50",
    border: "border-green-200",
    hoverBorder: "hover:border-green-400",
    category: "game",
  },
  {
    slug: "memory-match",
    title: "神経衰弱",
    shortTitle: "神経衰弱",
    emoji: "🃏",
    description: "カードをめくってペアを探せ！",
    image: "/api/og/memory-match",
    gradient: "from-fuchsia-400 to-pink-600",
    bgGradient: "from-fuchsia-50 to-pink-50",
    border: "border-fuchsia-200",
    hoverBorder: "hover:border-fuchsia-400",
    category: "game",
  },
  {
    slug: "rpg-job",
    title: "人生RPGジョブ診断",
    shortTitle: "RPGジョブ",
    emoji: "⚔️",
    description: "10問の冒険クエストであなたの人生ジョブが判明！",
    image: "/images/rpg-job/main.png",
    gradient: "from-amber-500 to-slate-800",
    bgGradient: "from-slate-900 to-slate-800",
    border: "border-amber-400",
    hoverBorder: "hover:border-amber-300",
    createdAt: "2026-02-02",
  },
  {
    slug: "zense",
    title: "前世診断",
    shortTitle: "前世診断",
    emoji: "🔮",
    description: "10問の質問であなたの前世の職業が判明！",
    image: "/images/zense/main.png",
    gradient: "from-amber-500 to-purple-500",
    bgGradient: "from-indigo-950 to-purple-900",
    border: "border-purple-400",
    hoverBorder: "hover:border-amber-300",
    createdAt: "2026-02-02",
  },
  {
    slug: "commu-style",
    title: "コミュニケーションスタイル診断",
    shortTitle: "コミュスタイル",
    emoji: "💬",
    description: "10個の質問であなたの伝え方のクセを診断！",
    image: "/images/commu-style/main.png",
    gradient: "from-amber-500 to-pink-500",
    bgGradient: "from-amber-50 to-pink-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
    createdAt: "2026-02-01",
  },
  {
    slug: "sainou",
    title: "隠れ才能診断",
    shortTitle: "隠れ才能",
    emoji: "💎",
    description: "10個の質問であなたの隠れた才能を発見！",
    image: "/images/sainou/main.png",
    gradient: "from-amber-500 to-purple-500",
    bgGradient: "from-amber-50 to-purple-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
    createdAt: "2026-02-02",
  },
  {
    slug: "hsp",
    title: "HSP診断",
    shortTitle: "HSP診断",
    emoji: "🌸",
    description: "10個の質問であなたの繊細さレベルを診断！",
    image: "/images/hsp/main.png",
    gradient: "from-purple-400 to-pink-400",
    bgGradient: "from-purple-50 to-pink-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
    createdAt: "2026-02-03",
  },
  {
    slug: "adhd",
    title: "ADHD傾向チェック",
    shortTitle: "ADHD傾向",
    emoji: "🚀",
    description: "10個の質問であなたのADHD傾向をチェック！",
    image: "/images/adhd/main.png",
    gradient: "from-orange-400 to-yellow-400",
    bgGradient: "from-orange-50 to-yellow-50",
    border: "border-orange-200",
    hoverBorder: "hover:border-orange-400",
    createdAt: "2026-02-03",
  },
  {
    slug: "asd",
    title: "ASD傾向チェック",
    shortTitle: "ASD傾向",
    emoji: "🔷",
    description: "10個の質問であなたのASD傾向をチェック！",
    image: "/images/asd/main.png",
    gradient: "from-blue-400 to-cyan-400",
    bgGradient: "from-blue-50 to-cyan-50",
    border: "border-blue-200",
    hoverBorder: "hover:border-blue-400",
    createdAt: "2026-02-03",
  },
  {
    slug: "color-diversity",
    title: "色覚多様性チェック",
    shortTitle: "色覚チェック",
    emoji: "🌈",
    description: "石原式風テストであなたの色覚タイプをチェック！",
    image: "/api/og/color-diversity",
    gradient: "from-red-400 via-green-400 to-blue-400",
    bgGradient: "from-red-50 via-green-50 to-blue-50",
    border: "border-purple-200",
    hoverBorder: "hover:border-purple-400",
    category: "game",
    createdAt: "2026-02-04",
  },
  {
    slug: "liar-test",
    title: "嘘つき度診断",
    shortTitle: "嘘つき度",
    emoji: "🎭",
    description: "回答の「迷い」を検出。あなたの嘘、バレてますよ？",
    image: "/images/liar-test/main.png",
    gradient: "from-gray-600 to-gray-900",
    bgGradient: "from-gray-50 to-slate-50",
    border: "border-gray-300",
    hoverBorder: "hover:border-gray-500",
    category: "shindan",
    createdAt: "2026-02-07",
  },
  {
    slug: "trolley-test",
    title: "思考の癖テスト",
    shortTitle: "思考の癖",
    emoji: "🧩",
    description: "トロッコ問題であなたの正義を可視化。功利主義 vs 義務論",
    image: "/images/trolley-test/main.png",
    gradient: "from-amber-500 to-orange-600",
    bgGradient: "from-amber-50 to-orange-50",
    border: "border-amber-200",
    hoverBorder: "hover:border-amber-400",
    category: "shindan",
    createdAt: "2026-02-07",
  },
  {
    slug: "dark-triad",
    title: "ダークサイド診断",
    shortTitle: "ダークサイド",
    emoji: "🖤",
    description: "あなたの中の「闇」を3軸で測定。ダークトライアド診断",
    image: "/images/dark-triad/main.png",
    gradient: "from-gray-800 to-purple-900",
    bgGradient: "from-gray-100 to-purple-50",
    border: "border-purple-300",
    hoverBorder: "hover:border-purple-500",
    category: "shindan",
    createdAt: "2026-02-07",
  },
  {
    slug: "subliminal-test",
    title: "潜在意識テスト",
    shortTitle: "潜在意識",
    emoji: "👁️",
    description: "0.1秒で見えたものが、本当のあなた。直感テスト。",
    image: "/images/subliminal-test/main.png",
    gradient: "from-indigo-500 to-purple-700",
    bgGradient: "from-indigo-50 to-purple-50",
    border: "border-indigo-200",
    hoverBorder: "hover:border-indigo-400",
    category: "shindan",
    createdAt: "2026-02-07",
  },
  {
    slug: "theomachia",
    title: "テオマキア - 神々の戦い",
    shortTitle: "テオマキア",
    emoji: "⚡",
    description: "神話カードで激突する2人対戦ゲーム！オンラインで友達と対戦しよう",
    image: "/theomachia/banner.png",
    gradient: "from-amber-400 to-yellow-600",
    bgGradient: "from-slate-900 to-indigo-950",
    border: "border-amber-300",
    hoverBorder: "hover:border-amber-400",
    category: "game",
    createdAt: "2026-02-07",
  },
  {
    slug: "gengoka-ryoku",
    title: "言語化力診断",
    shortTitle: "言語化力",
    emoji: "📝",
    description: "あなたの「言葉にする力」を6タイプで診断！",
    image: "/images/gengoka-ryoku/main.png",
    gradient: "from-cyan-400 to-blue-500",
    bgGradient: "from-cyan-50 to-blue-50",
    border: "border-cyan-200",
    hoverBorder: "hover:border-cyan-400",
    category: "shindan",
    createdAt: "2026-02-07",
  },
  {
    slug: "my-best/seiyuu",
    title: "私のベスト声優",
    shortTitle: "ベスト声優",
    emoji: "🎙️",
    description: "推し声優のベストキャラ3選を作ってシェアしよう！",
    image: "/api/og/my-best/seiyuu",
    gradient: "from-rose-400 to-violet-500",
    bgGradient: "from-rose-50 to-violet-50",
    border: "border-rose-200",
    hoverBorder: "hover:border-rose-400",
    category: "game",
    createdAt: "2026-03-05",
  },
];

export function getOtherDiagnoses(currentSlug: string): DiagnosisInfo[] {
  return diagnoses.filter((d) => d.slug !== currentSlug);
}

export function getDiagnosesByCategory(): {
  shindan: DiagnosisInfo[];
  game: DiagnosisInfo[];
} {
  return {
    shindan: diagnoses.filter((d) => !d.category || d.category === "shindan"),
    game: diagnoses.filter((d) => d.category === "game"),
  };
}

// 新着診断を取得（createdAtがあるものを日付順）
export function getNewestDiagnoses(limit: number = 6): DiagnosisInfo[] {
  return diagnoses
    .filter((d) => d.createdAt)
    .sort((a, b) => {
      if (!a.createdAt || !b.createdAt) return 0;
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    })
    .slice(0, limit);
}

// 人気診断を取得
export function getPopularDiagnoses(limit: number = 6): DiagnosisInfo[] {
  return popularDiagnosisSlugs
    .map((slug) => diagnoses.find((d) => d.slug === slug))
    .filter((d): d is DiagnosisInfo => d !== undefined)
    .slice(0, limit);
}

// 人気ゲームを取得
export function getPopularGames(limit: number = 6): DiagnosisInfo[] {
  return popularGameSlugs
    .map((slug) => diagnoses.find((d) => d.slug === slug))
    .filter((d): d is DiagnosisInfo => d !== undefined)
    .slice(0, limit);
}
